#!/usr/bin/env python3
"""Build the single-file Sugarscape broadcast viewer.

The Observatory embeds the replay in a sandboxed iframe behind the Kubernetes
service proxy, which rewrites the page's base href and cannot reach a CDN. A page
that pulls any separate sub-resource therefore renders as a black box. So this
tool folds the stylesheet, the script, the vendored typefaces and the whole art
batch into one self-contained document with every asset as a data URI, and writes
it to ``src/sugarscape/viewer.html`` where ``coworld.nim`` reads it at compile
time.

    python3 tools/build_viewer.py [--check]

``--check`` rebuilds into memory and fails if the committed output is stale,
which is what the test suite runs.
"""

from __future__ import annotations

import argparse
import base64
import io
import sys
from pathlib import Path

from PIL import Image, ImageChops

ROOT = Path(__file__).resolve().parent.parent
ART = ROOT / "src/sugarscape/art"
FONTS = ROOT / "src/sugarscape/fonts"
SOURCE = ROOT / "viewer"
OUTPUT = ROOT / "src/sugarscape/viewer.html"

def trim_border(image: Image.Image, tolerance: int = 26) -> Image.Image:
    """Drop the painted border the model likes to add around a framed vista."""
    rgb = image.convert("RGB")
    corner = Image.new("RGB", rgb.size, rgb.getpixel((2, 2)))
    difference = ImageChops.difference(rgb, corner).convert("L")
    box = difference.point(lambda value: 255 if value > tolerance else 0).getbbox()
    return rgb.crop(box) if box else rgb


def encode(image: Image.Image, fmt: str, **options: object) -> str:
    buffer = io.BytesIO()
    image.save(buffer, format=fmt, **options)
    mime = "image/png" if fmt == "PNG" else "image/jpeg"
    return f"data:{mime};base64,{base64.b64encode(buffer.getvalue()).decode()}"


def build_assets() -> dict[str, str]:
    """Process the raw batch into the sizes and formats the viewer actually draws."""
    assets: dict[str, str] = {}

    endcard = trim_border(Image.open(ART / "endcard.png"))
    endcard = endcard.resize((1280, int(1280 * endcard.height / endcard.width)), Image.LANCZOS)
    assets["endcard"] = encode(endcard, "JPEG", quality=72, optimize=True)
    return assets


def build_fonts() -> dict[str, str]:
    fonts = {}
    for path in sorted(FONTS.glob("*.woff2")):
        encoded = base64.b64encode(path.read_bytes()).decode()
        fonts[path.stem.replace("-", "_")] = f"data:font/woff2;base64,{encoded}"
    if not fonts:
        raise SystemExit("no vendored fonts; run tools/vendor_fonts.mjs first")
    return fonts


def substitute(template: str, tokens: dict[str, str]) -> str:
    for key, value in tokens.items():
        marker = "{{" + key + "}}"
        if marker not in template:
            raise SystemExit(f"template has no slot for {marker}")
        template = template.replace(marker, value)
    return template


def build() -> str:
    assets = build_assets()
    fonts = build_fonts()
    css = substitute((SOURCE / "broadcast.css").read_text(), fonts)
    script = (SOURCE / "broadcast.js").read_text()
    art_literal = ",\n".join(f'  {key}: "{value}"' for key, value in sorted(assets.items()))
    document = substitute(
        (SOURCE / "broadcast.html").read_text(),
        {
            "STYLE": css,
            "ART": f"const ART = {{\n{art_literal},\n}};",
            "SCRIPT": script,
        },
    )
    return (
        "<!-- Generated by tools/build_viewer.py from viewer/. Do not edit by hand. -->\n"
        + document
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the committed output is stale")
    arguments = parser.parse_args()

    document = build()
    if arguments.check:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != document:
            print(f"{OUTPUT} is stale; run: python3 tools/build_viewer.py", file=sys.stderr)
            return 1
        print(f"{OUTPUT} is up to date ({len(document) / 1024:.0f} KB)")
        return 0

    OUTPUT.write_text(document)
    print(f"{OUTPUT}  {len(document) / 1024:.0f} KB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
